from makeFigure1_Motivation import makeFigure1_Motivation
from makeFigure2_BasinMap import makeFigure2_BasinMap
from makeFigure3_HistoricalHMM import makeFigure3_HistoricalHMM
from makeFigure4_AllHMMparams import makeFigure4_AllHMMparams
from makeFigure5_AllFlowRanges import makeFigure5_AllFlowRanges
from makeFigure6_ShortageDistns import makeFigure6_ShortageDistns
from makeFigure7_VarianceDecomposition import makeFigure7_VarianceDecomposition
from makeFigure8_ResponseSurfaces import makeFigure8_ResponseSurfaces
from makeFigure9_FactorMaps import makeFigure9_FactorMaps
from makeFigure10_RobustnessRanks import makeFigure10_RobustnessRanks
from makeFigureS1_GaussianFits import makeFigureS1_GaussianFits
from makeFigureS2_MarkovFits import makeFigureS2_MarkovFits
from makeFigureS3_SpatialCorrelation import makeFigureS3_SpatialCorrelation
from makeFigureS4_IrrigationModel import makeFigureS4_IrrigationModel
from makeFigureS5_VICerrorModel import makeFigureS5_VICerrorModel
from makeFigureS6_VICparams import makeFigureS6_VICparams
from makeFigureS7_ReconstructionModel import makeFigureS7_ReconstructionModel
from makeFigureS8_ReconstructionParams import makeFigureS8_ReconstructionParams
from makeFigureS9_All5HMMparams import makeFigureS9_All5HMMparams
from makeFigureS10_VarianceDecomposition_User3 import makeFigureS10_VarianceDecomposition_User3
from makeFigureS11_CMIPcomparison import makeFigureS11_CMIPcomparison
from makeFigureS12_VarianceDecomposition_original_100 import makeFigureS12_VarianceDecomposition_original_100
from makeFigureS13_VarianceDecomposition_original_100 import makeFigureS13_VarianceDecomposition_original_100
from makeFigureS14_ResponseSurfaces_User2 import makeFigureS14_ResponseSurfaces_User2
from makeFigureS15_FactorMaps_User2 import makeFigureS15_FactorMaps_User2
from makeFigureS16_ResponseSurfaces_User3 import makeFigureS16_ResponseSurfaces_User3
from makeFigureS17_FactorMaps_User3 import makeFigureS17_FactorMaps_User3
from makeFigureS18_SatisficingSurfaces import makeFigureS18_SatisficingSurfaces
from makeFigureS19_SatisficingSurfaces_100samples import makeFigureS19_SatisficingSurfaces_100samples
from makeFigureS20_RobustnessRanks_100samples import makeFigureS20_RobustnessRanks_100samples

makeFigure1_Motivation()
makeFigure2_BasinMap()
makeFigure3_HistoricalHMM()
makeFigure4_AllHMMparams()
makeFigure5_AllFlowRanges()
makeFigure6_ShortageDistns()
makeFigure7_VarianceDecomposition()
makeFigure8_ResponseSurfaces()
makeFigure9_FactorMaps()
makeFigure10_RobustnessRanks()

makeFigureS1_GaussianFits()
makeFigureS2_MarkovFits()
makeFigureS3_SpatialCorrelation()
makeFigureS4_IrrigationModel()
makeFigureS5_VICerrorModel()
makeFigureS6_VICparams()
makeFigureS7_ReconstructionModel()
makeFigureS8_ReconstructionParams()
makeFigureS9_All5HMMparams()
makeFigureS10_VarianceDecomposition_User3()
makeFigureS11_CMIPcomparison()
makeFigureS12_VarianceDecomposition_original_100()
makeFigureS13_VarianceDecomposition_wider_100()
makeFigureS14_ResponseSurfaces_User2()
makeFigureS15_FactorMaps_User2()
makeFigureS16_ResponseSurfaces_User3()
makeFigureS17_FactorMaps_User3()
makeFigureS18_SatisficingSurfaces()
makeFigureS19_SatisficingSurfaces_100samples()
makeFigureS20_RobustnessRanks_100samples()